In [1]:
# Import Libraries
import pandas as pd
import numpy as np

# plotting
#import matplotlib.pyplot as plt
#import seaborn as sns

import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning) 

In [3]:
#Test Data
#df_test = pd.read_csv("PumpItUp/raw_data/702ddfc5-68cd-4d1d-a0de-f5f566f76d91.csv") 
#df_test.head(1)

In [4]:
# Load Data:
df = pd.read_csv("train_clean.csv")
df.head()

Unnamed: 0  amount_tsh  gps_height  num_private                    basin  \
0           0      6000.0        1390            0               Lake Nyasa   
1           1         0.0        1399            0            Lake Victoria   
2           2        25.0         686            0                  Pangani   
3           3         0.0         263            0  Ruvuma / Southern Coast   
4           4         0.0           0            0            Lake Victoria   

    region  region_code district_code_recoded  population public_meeting  ...  \
0   Iringa           11       Other Districts         109           True  ...   
1     Mara           20    District Codes 1-4         280            NaN  ...   
2  Manyara           21    District Codes 1-4         250           True  ...   
3   Mtwara           90       Other Districts          58           True  ...   
4   Kagera           18    District Codes 1-4           0           True  ...   

  management_group_recoded payment_recoded water_quality_recoded  \
0               user-group           other                  soft   
1               user-group       never pay                  soft   
2               user-group           other                  soft   
3               user-group       never pay                  soft   
4                    other       never pay                  soft   

   source_recoded source_type_recoded source_class_recoded  \
0          spring              spring          groundwater   
1           other               other              surface   
2           other               other              surface   
3           other            borehole          groundwater   
4           other               other              surface   

  waterpoint_type_recoded waterpoint_type_group_recoded quantity_recoded  \
0      communal standpipe            communal standpipe           enough   
1      communal standpipe            communal standpipe     insufficient   
2                   other            communal standpipe           enough   
3                   other            communal standpipe            other   
4      communal standpipe            communal standpipe            other   

     status_group  
0      functional  
1      functional  
2      functional  
3  non functional  
4      functional  

[5 rows x 28 columns]

In [5]:
df = df.drop('Unnamed: 0',axis=1)
df.head()

amount_tsh  gps_height  num_private                    basin   region  \
0      6000.0        1390            0               Lake Nyasa   Iringa   
1         0.0        1399            0            Lake Victoria     Mara   
2        25.0         686            0                  Pangani  Manyara   
3         0.0         263            0  Ruvuma / Southern Coast   Mtwara   
4         0.0           0            0            Lake Victoria   Kagera   

   region_code district_code_recoded  population public_meeting  \
0           11       Other Districts         109           True   
1           20    District Codes 1-4         280            NaN   
2           21    District Codes 1-4         250           True   
3           90       Other Districts          58           True   
4           18    District Codes 1-4           0           True   

               recorded_by  ... management_group_recoded payment_recoded  \
0  GeoData Consultants Ltd  ...               user-group           other   
1  GeoData Consultants Ltd  ...               user-group       never pay   
2  GeoData Consultants Ltd  ...               user-group           other   
3  GeoData Consultants Ltd  ...               user-group       never pay   
4  GeoData Consultants Ltd  ...                    other       never pay   

   water_quality_recoded source_recoded source_type_recoded  \
0                   soft         spring              spring   
1                   soft          other               other   
2                   soft          other               other   
3                   soft          other            borehole   
4                   soft          other               other   

  source_class_recoded waterpoint_type_recoded waterpoint_type_group_recoded  \
0          groundwater      communal standpipe            communal standpipe   
1              surface      communal standpipe            communal standpipe   
2              surface                   other            communal standpipe   
3          groundwater                   other            communal standpipe   
4              surface      communal standpipe            communal standpipe   

  quantity_recoded    status_group  
0           enough      functional  
1     insufficient      functional  
2           enough      functional  
3            other  non functional  
4            other      functional  

[5 rows x 27 columns]

In [22]:
# Change object data type into character data type
cols_cat_num = ['basin', 'region', 'district_code_recoded','public_meeting','recorded_by',
               'scheme_management_recoded','permit','extraction_type_recoded','extraction_type_group',
               'extraction_type_class','management_recoded','management_group_recoded',
               'payment_recoded','water_quality_recoded','source_recoded','source_type_recoded',
               'source_class_recoded','waterpoint_type_recoded','waterpoint_type_group_recoded',
               'quantity_recoded','status_group']

df[cols_cat_num] = df[cols_cat_num].astype('str')

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59400 entries, 0 to 59399
Data columns (total 27 columns):
 #   Column                         Non-Null Count  Dtype  
---  ------                         --------------  -----  
 0   amount_tsh                     59400 non-null  float64
 1   gps_height                     59400 non-null  int64  
 2   num_private                    59400 non-null  int64  
 3   basin                          59400 non-null  object 
 4   region                         59400 non-null  object 
 5   region_code                    59400 non-null  int64  
 6   district_code_recoded          59400 non-null  object 
 7   population                     59400 non-null  int64  
 8   public_meeting                 59400 non-null  object 
 9   recorded_by                    59400 non-null  object 
 10  scheme_management_recoded      59400 non-null  object 
 11  permit                         59400 non-null  object 
 12  construction_year              59400 non-null 

In [23]:
df_X = df.drop('status_group', axis=1)
df_X.head()

amount_tsh  gps_height  num_private                    basin   region  \
0      6000.0        1390            0               Lake Nyasa   Iringa   
1         0.0        1399            0            Lake Victoria     Mara   
2        25.0         686            0                  Pangani  Manyara   
3         0.0         263            0  Ruvuma / Southern Coast   Mtwara   
4         0.0           0            0            Lake Victoria   Kagera   

   region_code district_code_recoded  population public_meeting  \
0           11       Other Districts         109           True   
1           20    District Codes 1-4         280            nan   
2           21    District Codes 1-4         250           True   
3           90       Other Districts          58           True   
4           18    District Codes 1-4           0           True   

               recorded_by  ... management_recoded management_group_recoded  \
0  GeoData Consultants Ltd  ...                vwc               user-group   
1  GeoData Consultants Ltd  ...              other               user-group   
2  GeoData Consultants Ltd  ...                vwc               user-group   
3  GeoData Consultants Ltd  ...                vwc               user-group   
4  GeoData Consultants Ltd  ...              other                    other   

   payment_recoded water_quality_recoded source_recoded source_type_recoded  \
0            other                  soft         spring              spring   
1        never pay                  soft          other               other   
2            other                  soft          other               other   
3        never pay                  soft          other            borehole   
4        never pay                  soft          other               other   

  source_class_recoded waterpoint_type_recoded waterpoint_type_group_recoded  \
0          groundwater      communal standpipe            communal standpipe   
1              surface      communal standpipe            communal standpipe   
2              surface                   other            communal standpipe   
3          groundwater                   other            communal standpipe   
4              surface      communal standpipe            communal standpipe   

  quantity_recoded  
0           enough  
1     insufficient  
2           enough  
3            other  
4            other  

[5 rows x 26 columns]

In [24]:
df_y = df['status_group']
df_y.head()

0        functional
1        functional
2        functional
3    non functional
4        functional
Name: status_group, dtype: object

In [25]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

# one hot encode input variables
onehot_encoder = OneHotEncoder(sparse=False)
df_X = onehot_encoder.fit_transform(df_X)
# ordinal encode target variable
label_encoder = LabelEncoder()
df_y = label_encoder.fit_transform(df_y)
# summarize the transformed data
print('Input', df_X.shape)
print(df_X[:5, :])


Input (59400, 3813)
[[0. 0. 0. ... 1. 0. 0.]
 [1. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 [1. 0. 0. ... 0. 0. 1.]
 [1. 0. 0. ... 0. 0. 1.]]


In [27]:
# test classification dataset
from collections import Counter
from sklearn.datasets import make_classification

# summarize the dataset
print(df_X.shape, df_y.shape)
print(Counter(df_y))

(59400, 3813) (59400,)
Counter({0: 32259, 2: 22824, 1: 4317})


In [28]:
# evaluate multinomial logistic regression model
from numpy import mean
from numpy import std
from sklearn.datasets import make_classification
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.linear_model import LogisticRegression

# define dataset
#X, y = make_classification(n_samples=1000, n_features=10, n_informative=5, n_redundant=5, n_classes=3, random_state=1)

# define the multinomial logistic regression model
model = LogisticRegression(multi_class='multinomial', solver='lbfgs')

# define the model evaluation procedure
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)

# evaluate the model and collect the scores
n_scores = cross_val_score(model, df_X, df_y, scoring='accuracy', cv=cv, n_jobs=-1)

# report the model performance
print('Mean Accuracy: %.3f (%.3f)' % (mean(n_scores), std(n_scores)))

KeyboardInterrupt: 

In [10]:
# make a prediction with a multinomial logistic regression model
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression

# define dataset
#X, y = make_classification(n_samples=1000, n_features=10, n_informative=5, n_redundant=5, n_classes=3, random_state=1)

# define the multinomial logistic regression model
model = LogisticRegression(multi_class='multinomial', solver='lbfgs')

# fit the model on the whole dataset
model.fit(df_X, df_y)

# define a single row of input data
df_test = pd.read_csv("PumpItUp/raw_data/702ddfc5-68cd-4d1d-a0de-f5f566f76d91.csv") #Test Data
# need to recode some variables
row = df_test.head(1)

# predict the class label
yhat = model.predict([row])

# summarize the predicted class
print('Predicted Class: %d' % yhat[0])

ValueError: could not convert string to float: 'enough'

## References:

1. One-Hot Encoding: https://machinelearningmastery.com/one-hot-encoding-for-categorical-data/